-- ============================================================================
-- ALLIANCE HUB — ESQUEMA REAL EN PRODUCCION (sincronizado 2026-08-20)
-- Fuente: base de datos en vivo (proyecto qkccyjegkgjzwoxytnqp), NO teorico.
-- Este archivo es DOCUMENTACION del estado actual. La fuente de verdad es la
-- base de datos; este archivo se regenera tras cada migracion.
-- ============================================================================

-- ============================================================================
-- TABLAS (todas con RLS activo — verificado 2026-08-18)
-- ============================================================================

-- admin_users: cuentas administrativas (auth de Supabase)
--   id uuid PK (auth.uid), alliance_id uuid, display_name text,
--   supremacy_player_id bigint, approved_by uuid, approved_at timestamptz,
--   status text, created_at timestamptz, role text NOT NULL
-- RLS: SELECT is_admin() | INSERT/DELETE is_superadmin() |
--      UPDATE is_admin() + TRIGGER trg_protect_admin_users (solo superadmin
--      cambia role/status/alliance_id o filas ajenas; cada admin solo su
--      propio display_name)

-- admin_invites: codigos de invitacion (staff y lideres)
--   id uuid PK, code text, created_by uuid, used bool, used_by uuid,
--   used_at timestamptz, expires_at timestamptz, created_at timestamptz,
--   role text NOT NULL, player_id integer, alliance_id uuid
-- RLS: ALL is_authenticated_admin() | INSERT admin activo
--   (Sin lectura anon: ver RPCs get_player_invite / verify_leader_invite)

-- alliances
--   id uuid PK, name text NOT NULL, tag text NOT NULL, description text,
--   leader_id bigint, status text, created_at timestamptz
-- RLS: SELECT public | INSERT/UPDATE/DELETE admin activo
-- TRIGGER: trg_sanitize_alliances (anti-XSS en name/tag)

-- alliance_leader_requests: solicitudes publicas de liderazgo
--   id uuid PK, player_id bigint NOT NULL, display_name text NOT NULL,
--   supremacy_player_id bigint NOT NULL, alliance_name text NOT NULL,
--   alliance_tag text NOT NULL, evidence_url text, status text NOT NULL,
--   reviewed_by uuid, reviewed_at timestamptz, rejection_reason text,
--   invite_code_used uuid, created_at/updated_at timestamptz,
--   alliance_description text, discord_handle text, member_count int
-- RLS: SELECT/INSERT public (formulario abierto) | UPDATE/DELETE admin activo
-- TRIGGER: trg_sanitize_leader_req (anti-XSS)

-- alliance_memberships: membresias jugador<->alianza
--   id uuid PK, player_id bigint, alliance_id uuid, status text,
--   requested_by text, requested_at/approved_at/rejected_at timestamptz,
--   role text NOT NULL
-- RLS: SELECT public |
--      INSERT anon+auth WITH CHECK (status='pending' AND role IN (NULL,'member')) -- solicitud de union
--      DELETE anon+auth USING (status IN ('pending','rejected') AND role member)  -- cancelar solicitud
--      INSERT/UPDATE/DELETE admin (is_admin / admin activo)

-- alliance_officers: oficiales de alianza | RLS: ALL is_admin()
-- alliance_duel_teams: equipos de duelos   | RLS: ALL is_admin()
-- app_settings                             | RLS: SELECT public, INSERT/UPDATE admin
-- chat_channels                            | RLS: SELECT is_admin(), ALL superadmin
-- chat_messages                            | RLS: SELECT/INSERT/DELETE is_admin()
--   TRIGGER: trg_sanitize_chat (anti-XSS en sender_name/message)
-- chat_reports                             | RLS: SELECT/ALL is_admin() (sin lectura publica desde 2026-08-18)
--   TRIGGER: trg_sanitize_chat_reports (anti-XSS)
-- direct_messages                          | RLS: INSERT is_admin(), SELECT/UPDATE solo remitente/destinatario
-- leader_transfer_log                      | RLS: ALL is_admin()

-- matches: partidas/eventos
--   id uuid PK, name text NOT NULL, game_id text, description text,
--   alliance_id uuid, alliance_a_id/alliance_b_id uuid, round int,
--   max_players int, winners_declared bool, rules_url text, password text,
--   show_game_id bool, requires_approval bool, is_private bool,
--   share_token uuid, referee_id bigint, auto_delete_at timestamptz,
--   created_by uuid, csv_imported bool, notifications_sent bool,
--   created_at timestamptz, status text, match_type text, league_id uuid,
--   winner_alliance_id uuid,
--   category text NOT NULL DEFAULT 'alliance_hub'   -- 2026-08-27
--   whatsapp_url text                               -- 2026-08-27 (boton WhatsApp en partidas batallon)
--     CHECK (category IN ('alliance_hub','batallon'))
--     ('batallon' = Comunidad Batallon: inscripcion externa por WhatsApp,
--      badge/filtro en listados, importador de inscritos en admin)
-- RLS: SELECT public | INSERT is_admin() |
--      UPDATE/DELETE: superadmin/moderator/event_admin, o alliance_leader de
--      la alianza de la partida, o created_by = auth.uid()
-- TRIGGER: trg_sanitize_matches (anti-XSS)

-- match_registrations: inscripciones a partidas
--   id uuid PK, match_id uuid, player_id bigint, nation text,
--   registered_at/confirmed_at timestamptz, confirmed_by uuid, notes, status
--   UNIQUE (match_id, player_id)   -- 2026-08-27: un jugador no se registra
--     dos veces en la misma partida (constraint
--     match_registrations_match_player_unique)
-- RLS: SELECT public | escritura SOLO via RPCs player_register_match /
--      player_unregister_match (validan token de sesion en servidor) o admin

-- public_matches_view (vista publica de partidas, sin credenciales):
--   id, name, match_type, status, alliance_id, alliance_a_id, alliance_b_id,
--   league_id, max_players, winners_declared, requires_approval, is_private,
--   created_at, category   -- category anadida 2026-08-27 (AL FINAL)
--   WHERE status NOT IN ('draft','finished','archived')
--     AND match_type <> 'internal' AND is_private = false

-- match_results | RLS: SELECT public | INSERT is_admin() |
--   UPDATE/DELETE: superadmin/moderator/event_admin o lider de la alianza
-- match_winners | RLS: SELECT public (+ escritura admin via backend)
-- match_nullified_kills | RLS: SELECT public

-- players: jugadores (sin auth; identidad = id del juego real)
--   id bigint PK, current_username text NOT NULL, status text,
--   total_kills/total_deaths/games_played int, last_seen timestamptz,
--   created_at timestamptz, current_alliance_id uuid,
--   reputation_score int NOT NULL, suspension_reason text,
--   banned_until/suspended_until timestamptz
-- RLS: SELECT public | INSERT public WITH CHECK (status='active' AND
--      current_alliance_id IS NULL) | UPDATE solo admin activo
--   (el alta real y last_seen pasan por RPC player_login en servidor)
-- TRIGGER: trg_sanitize_players (anti-XSS en current_username)

-- player_tokens: SESIONES DE JUGADOR — TABLA SELLADA (sin politicas = sin
--   acceso anon/auth). Gestion exclusiva via RPCs security definer:
--   player_login (emite), verify_player_token (valida),
--   generate_transfer_code / claim_transfer_code (transferencia)
-- player_reports: reportes de jugadores
--   RLS: INSERT public (cualquiera reporta) | SELECT/UPDATE is_admin()
--   TRIGGER: trg_sanitize_reports (anti-XSS) + trg_push_new_report (push)
-- player_strikes | RLS: SELECT public (transparencia) |
--   INSERT/UPDATE superadmin/moderator/event_admin | DELETE superadmin
-- player_sanctions | RLS: SELECT public | ALL is_admin()
-- strike_types | RLS: SELECT public (activos) | ALL is_active_admin()
-- rule_sections | RLS: SELECT public (is_active) | ALL is_admin()
--   (sanitizacion y versionado via triggers rule_section_history)
-- rule_section_history | RLS: SELECT public | ALL is_authenticated_admin()
-- rule_precedents | RLS: SELECT public | INSERT superadmin/event_admin/
--   moderator | UPDATE/DELETE superadmin
-- training_progress | RLS: ALL is_admin()

-- push_config: configuracion de push (URL funcion, hook secret) — SELLADA
-- push_notification_log | RLS: SELECT is_admin() (dedupe server-side)
-- push_subscriptions | RLS: ALL is_admin() |
--   INSERT public WITH CHECK (endpoint https) | DELETE public (baja propia)
--   (baja segura real via RPC delete_push_subscription)

-- player_ranking_stats: vista/materializada de ranking | lectura publica

-- ============================================================================
-- FUNCIONES RPC (public schema)
-- ============================================================================
-- Seguridad de rol (SECURITY DEFINER, uso interno en RLS):
--   is_admin(), is_superadmin(), is_active_admin(), is_authenticated(),
--   is_authenticated_admin(), is_valid_player(player_id), is_setup_complete()
-- Sesion de jugador (SECURITY DEFINER, ejecutables por anon):
--   player_login(player_id, display_name) -> token
--     (multi-sesion desde 2026-08-23: cada login emite token nuevo SIN matar
--      otras sesiones; limpia tokens con >30 dias sin uso)
--   verify_player_token(player_id, token) -> bool (refresca last_used)
--   player_register_match(match_id, player_id, token) -> status
--   player_unregister_match(match_id, player_id, token) -> bool
--   generate_transfer_code(player_id, token) / claim_transfer_code(code)
--   get_player_invite(player_id) / verify_leader_invite(code)
--   delete_push_subscription(endpoint)
-- Internas (revocadas de anon/auth — solo service_role / triggers):
--   notify_push(subject_id, event), recompute_duel_winner(match_id),
--   create_invite_code(), complete_setup(), chat_fifo_prune_global(),
--   clear_expired_bans()
-- Mantenimiento/rankings (invoker, uso admin/backend):
--   recalc_all_players(), recalc_player_from_scratch(player_id),
--   recalc_player_stats(player_id), invalidate_player_stats(game, player),
--   delete_game_complete(game_uuid), force_schema_cache_refresh()
-- Anti-XSS: ah_strip_angle_brackets() — trigger generico que elimina < y >
--   de campos de texto controlados por usuarios (players, reports,
--   leader_requests, alliances, matches, chat_messages, chat_reports)
-- Anti-escalada: trg_protect_admin_users() (ver admin_users arriba)

-- ============================================================================
-- admin_audit_log: log INMUTABLE de acciones admin (2026-08-20)
--   Quien (actor_id/actor_name), que (INSERT/UPDATE/DELETE), donde (table_name, row_id),
--   valor anterior y nuevo (jsonb), cuando. RLS: SELECT is_admin(); nadie escribe/borra
--   via API. Triggers trg_audit_* en: rule_sections, rule_precedents, strike_types,
--   player_strikes, player_sanctions, player_reports, chat_reports, matches, alliances,
--   admin_users, match_results. Funcion: ah_audit_admin_change() (security definer).

-- ============================================================================
-- STORAGE (buckets)
-- ============================================================================
-- evidence, report-evidence
--   INSERT public (jugadores suben evidencia sin cuenta)
--   DELETE/UPDATE solo admin
--   public = false (privados desde 2026-08-19)
--   SELECT solo admin (policy evidence_select_admin, is_admin())
--   Cliente: storage-utils.js firma URLs (createSignedUrl, expira 1h)
-- public-assets (2026-08-23)
--   Bucket publico de lectura para documentos (guias PDF, etc.)
--   SELECT publico; INSERT solo authenticated

-- ============================================================================
-- NOTAS DE DISENO (decisiones deliberadas, no huecos)
-- ============================================================================
-- 1. Lectura publica de players/matches/results/rankings/strikes/sanctions:
--    transparencia del sistema competitivo. La escritura es lo protegido.
-- 2. INSERT public de player_reports / alliance_leader_requests / evidencia:
--    el modelo permite participar sin cuenta. El cruce con la API del juego
--    real invalida registros falsos.
-- 3. La seguridad NO depende del frontend: toda la autorizacion vive en
--    RLS + RPCs + Edge Functions. requireAdmin() en JS es solo UI.
-- 4. La anon key en el repo es publica por diseno; lo que puede hacer esta
--    limitado por estas politicas. Historial Git auditado 2026-08-18: limpio.
-- ============================================================================
